name: bankingsim
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  google_fonts: ^3.0.1
  get: ^4.6.5
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo1.png
    - assets/google.png
    - assets/forget.png
    - assets/123.png




